### ISSUE TITLE
Does ue4-docker support offscreen rendering with Vulkan?

### ISSUE THREAD

**Issue by saihv** [adamrehn/ue4-docker#76]
I am trying to get some packaged binaries (Packaged with 4.24.3) to run on Docker, and have been running into many issues that are Vulkan related even after making sure the Vulkan API version, Nvidia driver version all match the expected ones. OpenGL rendering does work, but I am specifically interested in Vulkan. Is offscreen rendering with Vulkan supported for the ue4-docker images?

**Comment by adamrehn** [comment]
No, both the ue4-docker container images and the [ue4-runtime](https://github.com/adamrehn/ue4-runtime) image variants are based on the [nvidia/opengl](https://hub.docker.com/r/nvidia/opengl) and [nvidia/cudagl](https://hub.docker.com/r/nvidia/cudagl) base images, which only support OpenGL.

NVIDIA have been promising Vulkan support in GPU-accelerated containers for several years now, and do indeed have [the required plumbing under the hood](https://github.com/NVIDIA/libnvidia-container/pull/62), but the only official image available on Docker Hub that leverages that support is a very early alpha of a [Vulkan base image](https://hub.docker.com/r/nvidia/vulkan), which at the time of writing has not been updated in six months. I've been hesitant to test it myself until it reaches beta quality, but in theory you should be able to simply copy your packaged binaries into that alpha image and create a non-root user to run the packaged project as (since UE4 is hardcoded to refuse to run as the root user.)

**Comment by Clockwork-Muse** [comment]
I've made some really trivial attempts to get the alpha images working, without much success.  Among other things, the images aren't repeatable, so, since they haven't published an 18.04 image, getting it to build requires changes.

@saihv - if you get it working, please let me know what you did!

**Comment by saihv** [comment]
Unfortunately, I haven't had much luck either. I tried upgrading the Vulkan alpha image to 18.04, and after a lot of tweaking, got to the point where `vulkaninfo` worked fine, but even with that setup, UE would refuse to work. The errors were mostly around `VK_ERROR_INITIALIZATION_FAILED`, even though I was running Docker locally and tried setting the `$DISPLAY` parameter.

**Comment by adamrehn** [comment]
Okay, after investigating this further myself, I've figured out how to get offscreen rendering working with Vulkan. Here are the requirements:

- You'll need to use **Unreal Engine 4.25** (currently in preview at the time of writing), since offscreen rendering with Vulkan under Linux is actually broken in Unreal Engine 4.24, irrespective of whether it's running inside a container or directly on the host system. It's worth noting that Unreal Engine 4.25.0 Preview 7 fails to build its DDC successfully under Linux, so you can't actually build container images for it with ue4-docker yet, but this should be fixed in the final 4.25.0 release.

- You'll need a container image with Vulkan support. In addition to [NVIDIA's alpha Vulkan base image](https://hub.docker.com/r/nvidia/vulkan), I'm also providing the following options:
   
   - The latest builds of the [ue4-runtime](https://github.com/adamrehn/ue4-runtime) now include Vulkan support and are [up on Docker Hub](https://hub.docker.com/r/adamrehn/ue4-runtime). **This is the recommended image for running packaged Unreal projects.**
   
   - As of ue4-docker version 0.0.61, the [ue4-full](https://adamrehn.com/docs/ue4-docker/building-images/available-container-images#ue4-full) image also includes Vulkan support. (Again, not useful for offscreen rendering with the 4.25 preview, but will be useful when 4.25.0 officially releases and can still be used for windowed Vulkan rendering with 4.24 if you bind-mount the X11 socket from the host system.)

**Comment by Clockwork-Muse** [comment]
> It's worth noting that Unreal Engine 4.25.0 Preview 7 fails to build its DDC successfully under Linux, so you can't actually build container images for it with ue4-docker yet, but this should be fixed in the final 4.25.0 release.

... this still fails, but I'm not altogether sure why, given that the errors are listing declarations that should be present/valid anyways...

**Comment by adamrehn** [comment]
@Clockwork-Muse yes, apparently the fix didn't make it into 4.25.0 and is due to land in 4.25.1. In the meantime, you can use the `--exclude ddc` flag added in ue4-docker version 0.0.62 to disable DDC generation and build container images successfully for 4.25.0.

**Comment by Clockwork-Muse** [comment]
Yes (although packaging a project still fails, because it has to build the ddc at that point).

**Comment by clintlombard** [comment]
I can confirm that the latest release (4.25.3) works with off screen rendering on Linux.

**Comment by jeffreyng99** [comment]
@clintlombard Can you explain the steps you took so I can reproduce this? Thanks in advance.

**Comment by clintlombard** [comment]
Setting `NVIDIA_DRIVER_CAPABILITIES` liberally and updating `nvidia_icd.json` after installing the `vulkan-sdk` did the trick:
```dockerfile
# Enable Vulkan support
ARG VULKAN_VERSION="1.2.148"
ENV NVIDIA_DRIVER_CAPABILITIES compute,graphics,utility,display
RUN export $(cat /etc/os-release | grep --color=never 'UBUNTU_CODENAME') && \
    wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | apt-key add - && \
    wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${VULKAN_VERSION}-${UBUNTU_CODENAME}.list \
    https://packages.lunarg.com/vulkan/${VULKAN_VERSION}/lunarg-vulkan-${VULKAN_VERSION}-${UBUNTU_CODENAME}.list && \
    apt-get update && apt-get install -y --no-install-recommends vulkan-sdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN VULKAN_API_VERSION=`dpkg -s libvulkan1 | grep -oP 'Version: [0-9|\.]+' | grep -oP '[0-9|\.]+'` && \
    mkdir -p /etc/vulkan/icd.d/ && \
    echo \
    "{\
        \"file_format_version\" : \"1.0.0\",\
        \"ICD\": {\
            \"library_path\": \"libGLX_nvidia.so.0\",\
            \"api_version\" : \"${VULKAN_API_VERSION}\"\
        }\
    }" > /etc/vulkan/icd.d/nvidia_icd.json
```
Sources:
* https://gitlab.com/nvidia/container-images/vulkan
* https://github.com/adamrehn/ue4-docker/blob/master/ue4docker/dockerfiles/ue4-full/linux/Dockerfile

**Comment by Code-Guy** [comment]
> Setting `NVIDIA_DRIVER_CAPABILITIES` liberally and updating `nvidia_icd.json` after installing the `vulkan-sdk` did the trick:
> 
> ```dockerfile
> # Enable Vulkan support
> ARG VULKAN_VERSION="1.2.148"
> ENV NVIDIA_DRIVER_CAPABILITIES compute,graphics,utility,display
> RUN export $(cat /etc/os-release | grep --color=never 'UBUNTU_CODENAME') && \
>     wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | apt-key add - && \
>     wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${VULKAN_VERSION}-${UBUNTU_CODENAME}.list \
>     https://packages.lunarg.com/vulkan/${VULKAN_VERSION}/lunarg-vulkan-${VULKAN_VERSION}-${UBUNTU_CODENAME}.list && \
>     apt-get update && apt-get install -y --no-install-recommends vulkan-sdk && \
>     apt-get clean && \
>     rm -rf /var/lib/apt/lists/*
> RUN VULKAN_API_VERSION=`dpkg -s libvulkan1 | grep -oP 'Version: [0-9|\.]+' | grep -oP '[0-9|\.]+'` && \
>     mkdir -p /etc/vulkan/icd.d/ && \
>     echo \
>     "{\
>         \"file_format_version\" : \"1.0.0\",\
>         \"ICD\": {\
>             \"library_path\": \"libGLX_nvidia.so.0\",\
>             \"api_version\" : \"${VULKAN_API_VERSION}\"\
>         }\
>     }" > /etc/vulkan/icd.d/nvidia_icd.json
> ```
> 
> Sources:
> 
> * https://gitlab.com/nvidia/container-images/vulkan
> * https://github.com/adamrehn/ue4-docker/blob/master/ue4docker/dockerfiles/ue4-full/linux/Dockerfile

@clintlombard Can you show your full dockerfile for buliding ue4 packaged binary? Many thanks! I tried a lot but with no luck:( there is always one error:"Failed to load Vulkan Driver which is required to run the engine"

**Comment by Clockwork-Muse** [comment]
@Code-Guy - That's probably more likely due to how you're **running** the image.  Did you remember to include the `--gpus=all` flag?

**Comment by Code-Guy** [comment]
Yes! I missed&nbsp;--gpus=all&nbsp;flag&nbsp;Thank you very much!




------------------&nbsp;Original message&nbsp;------------------
From: "Stephen A. Imhoff"; 
Sendtime: Thursday, Nov 26, 2020 1:08 AM
To: "adamrehn/ue4-docker"; 
Cc: "健哥"<1964875003@qq.com>; "Mention"; 
Subject: Re: [adamrehn/ue4-docker] Does ue4-docker support offscreen rendering with Vulkan? (#76)





 
@Code-Guy - That's probably more likely due to how you're running the image.  Did you remember to include the --gpus=all flag?
